services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8081:8080"
    environment:
      # These should match the values in config.yaml or be overridden by environment variables
      # For Docker Compose, it's common to pass them as environment variables
      SERVER_PORT: ":8080"
      DATABASE_URL: "mongodb://mongodb:27017"
      DATABASE_NAME: "recipes_db"
      DATABASE_COLLECTION: "recipes"
    depends_on:
      - mongodb
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: